import { MCPTool } from '../../../types/mcp';

const shipmentWasteCompositionTools: MCPTool[] = [
  // Shipment Waste Composition tools
  {
    name: 'shipment_waste_compositions_create',
    description: 'Create a new shipment waste composition record',
    inputSchema: {
      type: 'object',
      properties: {
        id: { type: 'string', description: 'MongoDB ObjectId' },
        client_id: { type: 'string', description: 'Client MongoDB ObjectId' },
        shipment_id: { type: 'string', description: 'Shipment MongoDB ObjectId' },
        facility_id: { type: 'string', description: 'Facility MongoDB ObjectId' },
        bunker_id: { type: 'string', description: 'Bunker MongoDB ObjectId' },
        
        // Basic composition fields
        moisture_level: { type: 'string', enum: ['LOW', 'MEDIUM', 'HIGH', 'NONE'], description: 'Moisture level' },
        moisture_comment: { type: 'string', description: 'Moisture comment' },
        dust_load_level: { type: 'string', enum: ['LOW', 'MEDIUM', 'HIGH', 'NONE'], description: 'Dust load level' },
        dust_load_comment: { type: 'string', description: 'Dust load comment' },
        calorific_value_min: { type: 'number', description: 'Minimum calorific value' },
        calorific_value_max: { type: 'number', description: 'Maximum calorific value' },
        calorific_value_comment: { type: 'string', description: 'Calorific value comment' },
        biogenic_content_percentage: { type: 'number', description: 'Biogenic content percentage' },
        biogenic_content_comment: { type: 'string', description: 'Biogenic content comment' },
        sulfur_dioxide_risk: { type: 'string', enum: ['LOW', 'MEDIUM', 'HIGH', 'NONE'], description: 'Sulfur dioxide risk' },
        sulfur_dioxide_comment: { type: 'string', description: 'Sulfur dioxide comment' },
        hydrochloric_acid_risk: { type: 'string', enum: ['LOW', 'MEDIUM', 'HIGH', 'NONE'], description: 'Hydrochloric acid risk' },
        hydrochloric_acid_comment: { type: 'string', description: 'Hydrochloric acid comment' },
        mono_charge_detected: { type: 'boolean', description: 'Mono charge detected' },
        mono_charge_comment: { type: 'string', description: 'Mono charge comment' },
        likely_ewc_code: { type: 'string', description: 'Likely EWC code' },
        likely_ewc_description: { type: 'string', description: 'Likely EWC description' },
        likely_ewc_comment: { type: 'string', description: 'Likely EWC comment' },
        
        // Material composition fields (32 fields)
        concrete_stones: { type: 'number', description: 'Concrete stones percentage' },
        concrete_stones_comment: { type: 'string', description: 'Concrete stones comment' },
        glass: { type: 'number', description: 'Glass percentage' },
        glass_comment: { type: 'string', description: 'Glass comment' },
        gypsum_board: { type: 'number', description: 'Gypsum board percentage' },
        gypsum_board_comment: { type: 'string', description: 'Gypsum board comment' },
        mineral_fibres: { type: 'number', description: 'Mineral fibres percentage' },
        mineral_fibres_comment: { type: 'string', description: 'Mineral fibres comment' },
        bitumen_roofing_felt: { type: 'number', description: 'Bitumen roofing felt percentage' },
        bitumen_roofing_felt_comment: { type: 'string', description: 'Bitumen roofing felt comment' },
        insulation_foams: { type: 'number', description: 'Insulation foams percentage' },
        insulation_foams_comment: { type: 'string', description: 'Insulation foams comment' },
        hbcd_materials: { type: 'number', description: 'HBCD materials percentage' },
        hbcd_materials_comment: { type: 'string', description: 'HBCD materials comment' },
        paper_moist: { type: 'number', description: 'Paper moist percentage' },
        paper_moist_comment: { type: 'string', description: 'Paper moist comment' },
        msw_wet: { type: 'number', description: 'MSW wet percentage' },
        msw_wet_comment: { type: 'string', description: 'MSW wet comment' },
        msw_mixed: { type: 'number', description: 'MSW mixed percentage' },
        msw_mixed_comment: { type: 'string', description: 'MSW mixed comment' },
        garden_household_furniture: { type: 'number', description: 'Garden household furniture percentage' },
        garden_household_furniture_comment: { type: 'string', description: 'Garden household furniture comment' },
        mattresses: { type: 'number', description: 'Mattresses percentage' },
        mattresses_comment: { type: 'string', description: 'Mattresses comment' },
        carpets: { type: 'number', description: 'Carpets percentage' },
        carpets_comment: { type: 'string', description: 'Carpets comment' },
        wallpaper: { type: 'number', description: 'Wallpaper percentage' },
        wallpaper_comment: { type: 'string', description: 'Wallpaper comment' },
        wood_ai_aii: { type: 'number', description: 'Wood AI AII percentage' },
        wood_ai_aii_comment: { type: 'string', description: 'Wood AI AII comment' },
        wood_aiii: { type: 'number', description: 'Wood AIII percentage' },
        wood_aiii_comment: { type: 'string', description: 'Wood AIII comment' },
        wood_aiv: { type: 'number', description: 'Wood AIV percentage' },
        wood_aiv_comment: { type: 'string', description: 'Wood AIV comment' },
        hard_plastics: { type: 'number', description: 'Hard plastics percentage' },
        hard_plastics_comment: { type: 'string', description: 'Hard plastics comment' },
        vehicle_parts_pipes: { type: 'number', description: 'Vehicle parts pipes percentage' },
        vehicle_parts_pipes_comment: { type: 'string', description: 'Vehicle parts pipes comment' },
        films_dirty_pe_pp: { type: 'number', description: 'Films dirty PE PP percentage' },
        films_dirty_pe_pp_comment: { type: 'string', description: 'Films dirty PE PP comment' },
        big_bags_pp_fabric: { type: 'number', description: 'Big bags PP fabric percentage' },
        big_bags_pp_fabric_comment: { type: 'string', description: 'Big bags PP fabric comment' },
        canisters_barrels: { type: 'number', description: 'Canisters barrels percentage' },
        canisters_barrels_comment: { type: 'string', description: 'Canisters barrels comment' },
        lightweight_packaging_lwp: { type: 'number', description: 'Lightweight packaging LWP percentage' },
        lightweight_packaging_lwp_comment: { type: 'string', description: 'Lightweight packaging LWP comment' },
        composite_packaging: { type: 'number', description: 'Composite packaging percentage' },
        composite_packaging_comment: { type: 'string', description: 'Composite packaging comment' },
        pvc_items: { type: 'number', description: 'PVC items percentage' },
        pvc_items_comment: { type: 'string', description: 'PVC items comment' },
        textiles_clothing: { type: 'number', description: 'Textiles clothing percentage' },
        textiles_clothing_comment: { type: 'string', description: 'Textiles clothing comment' },
        aluminium_shavings_comb: { type: 'number', description: 'Aluminium shavings comb percentage' },
        aluminium_shavings_comb_comment: { type: 'string', description: 'Aluminium shavings comb comment' },
        iron_fe: { type: 'number', description: 'Iron Fe percentage' },
        iron_fe_comment: { type: 'string', description: 'Iron Fe comment' },
        copper_cu: { type: 'number', description: 'Copper Cu percentage' },
        copper_cu_comment: { type: 'string', description: 'Copper Cu comment' },
        gfrp_cfrp: { type: 'number', description: 'GFRP CFRP percentage' },
        gfrp_cfrp_comment: { type: 'string', description: 'GFRP CFRP comment' },
        rubber_mixed: { type: 'number', description: 'Rubber mixed percentage' },
        rubber_mixed_comment: { type: 'string', description: 'Rubber mixed comment' },
        sludges_fines: { type: 'number', description: 'Sludges fines percentage' },
        sludges_fines_comment: { type: 'string', description: 'Sludges fines comment' },
        
        // Additional fields
        gcp_image_path: { type: 'string', description: 'Google Cloud Platform image path' },
      },
      required: ['id', 'client_uid', 'shipment_uid', 'facility_uid', 'bunker_uid'],
    },
  },
  {
    name: 'shipment_waste_compositions_get',
    description: 'Get a shipment waste composition by ID',
    inputSchema: {
      type: 'object',
      properties: {
        id: { type: 'string', description: 'MongoDB ObjectId' },
      },
      required: ['id'],
    },
  },
  {
    name: 'shipment_waste_compositions_update',
    description: 'Update a shipment waste composition record',
    inputSchema: {
      type: 'object',
      properties: {
        id: { type: 'string', description: 'MongoDB ObjectId' },
        
        // Basic composition fields
        moisture_level: { type: 'string', enum: ['LOW', 'MEDIUM', 'HIGH', 'NONE'], description: 'Moisture level' },
        moisture_comment: { type: 'string', description: 'Moisture comment' },
        dust_load_level: { type: 'string', enum: ['LOW', 'MEDIUM', 'HIGH', 'NONE'], description: 'Dust load level' },
        dust_load_comment: { type: 'string', description: 'Dust load comment' },
        calorific_value_min: { type: 'number', description: 'Minimum calorific value' },
        calorific_value_max: { type: 'number', description: 'Maximum calorific value' },
        calorific_value_comment: { type: 'string', description: 'Calorific value comment' },
        biogenic_content_percentage: { type: 'number', description: 'Biogenic content percentage' },
        biogenic_content_comment: { type: 'string', description: 'Biogenic content comment' },
        sulfur_dioxide_risk: { type: 'string', enum: ['LOW', 'MEDIUM', 'HIGH', 'NONE'], description: 'Sulfur dioxide risk' },
        sulfur_dioxide_comment: { type: 'string', description: 'Sulfur dioxide comment' },
        hydrochloric_acid_risk: { type: 'string', enum: ['LOW', 'MEDIUM', 'HIGH', 'NONE'], description: 'Hydrochloric acid risk' },
        hydrochloric_acid_comment: { type: 'string', description: 'Hydrochloric acid comment' },
        mono_charge_detected: { type: 'boolean', description: 'Mono charge detected' },
        mono_charge_comment: { type: 'string', description: 'Mono charge comment' },
        likely_ewc_code: { type: 'string', description: 'Likely EWC code' },
        likely_ewc_description: { type: 'string', description: 'Likely EWC description' },
        likely_ewc_comment: { type: 'string', description: 'Likely EWC comment' },
        
        // Material composition fields (32 fields)
        concrete_stones: { type: 'number', description: 'Concrete stones percentage' },
        concrete_stones_comment: { type: 'string', description: 'Concrete stones comment' },
        glass: { type: 'number', description: 'Glass percentage' },
        glass_comment: { type: 'string', description: 'Glass comment' },
        gypsum_board: { type: 'number', description: 'Gypsum board percentage' },
        gypsum_board_comment: { type: 'string', description: 'Gypsum board comment' },
        mineral_fibres: { type: 'number', description: 'Mineral fibres percentage' },
        mineral_fibres_comment: { type: 'string', description: 'Mineral fibres comment' },
        bitumen_roofing_felt: { type: 'number', description: 'Bitumen roofing felt percentage' },
        bitumen_roofing_felt_comment: { type: 'string', description: 'Bitumen roofing felt comment' },
        insulation_foams: { type: 'number', description: 'Insulation foams percentage' },
        insulation_foams_comment: { type: 'string', description: 'Insulation foams comment' },
        hbcd_materials: { type: 'number', description: 'HBCD materials percentage' },
        hbcd_materials_comment: { type: 'string', description: 'HBCD materials comment' },
        paper_moist: { type: 'number', description: 'Paper moist percentage' },
        paper_moist_comment: { type: 'string', description: 'Paper moist comment' },
        msw_wet: { type: 'number', description: 'MSW wet percentage' },
        msw_wet_comment: { type: 'string', description: 'MSW wet comment' },
        msw_mixed: { type: 'number', description: 'MSW mixed percentage' },
        msw_mixed_comment: { type: 'string', description: 'MSW mixed comment' },
        garden_household_furniture: { type: 'number', description: 'Garden household furniture percentage' },
        garden_household_furniture_comment: { type: 'string', description: 'Garden household furniture comment' },
        mattresses: { type: 'number', description: 'Mattresses percentage' },
        mattresses_comment: { type: 'string', description: 'Mattresses comment' },
        carpets: { type: 'number', description: 'Carpets percentage' },
        carpets_comment: { type: 'string', description: 'Carpets comment' },
        wallpaper: { type: 'number', description: 'Wallpaper percentage' },
        wallpaper_comment: { type: 'string', description: 'Wallpaper comment' },
        wood_ai_aii: { type: 'number', description: 'Wood AI AII percentage' },
        wood_ai_aii_comment: { type: 'string', description: 'Wood AI AII comment' },
        wood_aiii: { type: 'number', description: 'Wood AIII percentage' },
        wood_aiii_comment: { type: 'string', description: 'Wood AIII comment' },
        wood_aiv: { type: 'number', description: 'Wood AIV percentage' },
        wood_aiv_comment: { type: 'string', description: 'Wood AIV comment' },
        hard_plastics: { type: 'number', description: 'Hard plastics percentage' },
        hard_plastics_comment: { type: 'string', description: 'Hard plastics comment' },
        vehicle_parts_pipes: { type: 'number', description: 'Vehicle parts pipes percentage' },
        vehicle_parts_pipes_comment: { type: 'string', description: 'Vehicle parts pipes comment' },
        films_dirty_pe_pp: { type: 'number', description: 'Films dirty PE PP percentage' },
        films_dirty_pe_pp_comment: { type: 'string', description: 'Films dirty PE PP comment' },
        big_bags_pp_fabric: { type: 'number', description: 'Big bags PP fabric percentage' },
        big_bags_pp_fabric_comment: { type: 'string', description: 'Big bags PP fabric comment' },
        canisters_barrels: { type: 'number', description: 'Canisters barrels percentage' },
        canisters_barrels_comment: { type: 'string', description: 'Canisters barrels comment' },
        lightweight_packaging_lwp: { type: 'number', description: 'Lightweight packaging LWP percentage' },
        lightweight_packaging_lwp_comment: { type: 'string', description: 'Lightweight packaging LWP comment' },
        composite_packaging: { type: 'number', description: 'Composite packaging percentage' },
        composite_packaging_comment: { type: 'string', description: 'Composite packaging comment' },
        pvc_items: { type: 'number', description: 'PVC items percentage' },
        pvc_items_comment: { type: 'string', description: 'PVC items comment' },
        textiles_clothing: { type: 'number', description: 'Textiles clothing percentage' },
        textiles_clothing_comment: { type: 'string', description: 'Textiles clothing comment' },
        aluminium_shavings_comb: { type: 'number', description: 'Aluminium shavings comb percentage' },
        aluminium_shavings_comb_comment: { type: 'string', description: 'Aluminium shavings comb comment' },
        iron_fe: { type: 'number', description: 'Iron Fe percentage' },
        iron_fe_comment: { type: 'string', description: 'Iron Fe comment' },
        copper_cu: { type: 'number', description: 'Copper Cu percentage' },
        copper_cu_comment: { type: 'string', description: 'Copper Cu comment' },
        gfrp_cfrp: { type: 'number', description: 'GFRP CFRP percentage' },
        gfrp_cfrp_comment: { type: 'string', description: 'GFRP CFRP comment' },
        rubber_mixed: { type: 'number', description: 'Rubber mixed percentage' },
        rubber_mixed_comment: { type: 'string', description: 'Rubber mixed comment' },
        sludges_fines: { type: 'number', description: 'Sludges fines percentage' },
        sludges_fines_comment: { type: 'string', description: 'Sludges fines comment' },
        
        // Additional fields
        gcp_image_path: { type: 'string', description: 'Google Cloud Platform image path' },
        merged_at: { type: 'string', format: 'date-time', description: 'Merge timestamp' },
        merged_by_uid: { type: 'string', description: 'Merge user UID' },
        merged_from_shipment_uid: { type: 'string', description: 'Original shipment UID' },
      },
      required: ['id'],
    },
  },
  {
    name: 'shipment_waste_compositions_delete',
    description: 'Delete a shipment waste composition record',
    inputSchema: {
      type: 'object',
      properties: {
        id: { type: 'string', description: 'MongoDB ObjectId' },
      },
      required: ['id'],
    },
  },
  {
    name: 'shipment_waste_compositions_list',
    description: 'List shipment waste compositions with optional filters',
    inputSchema: {
      type: 'object',
      properties: {
        client_uid: { type: 'string', description: 'Filter by client ID' },
        shipment_uid: { type: 'string', description: 'Filter by shipment ID' },
        facility_uid: { type: 'string', description: 'Filter by facility ID' },
        bunker_uid: { type: 'string', description: 'Filter by bunker ID' },
        moisture_level: { type: 'string', enum: ['LOW', 'MEDIUM', 'HIGH', 'NONE'], description: 'Filter by moisture level' },
        sulfur_dioxide_risk: { type: 'string', enum: ['LOW', 'MEDIUM', 'HIGH', 'NONE'], description: 'Filter by sulfur dioxide risk' },
        date_from: { type: 'string', format: 'date-time', description: 'Filter from date' },
        date_to: { type: 'string', format: 'date-time', description: 'Filter to date' },
        // Material composition filters
        has_glass: { type: 'boolean', description: 'Filter compositions with glass content' },
        has_plastics: { type: 'boolean', description: 'Filter compositions with plastic content' },
        has_metals: { type: 'boolean', description: 'Filter compositions with metal content' },
        has_organic: { type: 'boolean', description: 'Filter compositions with organic content' },
        min_calorific_value: { type: 'number', description: 'Minimum calorific value filter' },
        max_calorific_value: { type: 'number', description: 'Maximum calorific value filter' },
        page: { type: 'number', description: 'Page number' },
        limit: { type: 'number', description: 'Items per page' },
      },
      required: ['page', 'limit'],
    },
  },
];

export default shipmentWasteCompositionTools;